[package]
name = "MultiThreadedServer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
num_cpus = "1.0"

[lib]
name = "MultiThreadedServer"
path = "src/lib.rs"
